### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by chongming-ni** [aramis-lab/clinicadl#16]
Hi  there @mdiazmel,
Thanks for developing such great software. I encountered a problem when preprocessing data. Below is a crash example. It said the file ADNI_BIDS/sub-ADNI036S1135/ses-M06/anat/sub-ADNI036S1135_ses-M06_T1w.nii.gz does not exist. However, the file does exist:

```
xxx@xxx:~/adni$ ls -lh ADNI_BIDS/sub-ADNI011S1080/ses-M24/anat/sub-ADNI011S1080_ses-M24_T1w.nii.gz
-rwxrwxr-x 1 xxx xxx 12M May 27 20:55 ADNI_BIDS/sub-ADNI011S1080/ses-M24/anat/sub-ADNI011S1080_ses-M24_T1w.nii.gz
```

```
save_bias = True
shrink_factor = <undefined>
weight_image = <undefined>
Traceback: 
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__
    mp_context=mp_context,
TypeError: __init__() got an unexpected keyword argument 'initializer'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/home/xxx/anaconda3/envs/adni/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
N4BiasFieldCorrection --bspline-fitting [ 600 ] -d 3 --input-image ADNI_BIDS/sub-ADNI011S1080/ses-M24/anat/sub-ADNI011S1080_ses-M24_T1w.nii.gz --output [ sub-ADNI011S1080_ses-M24_T1w_corrected.nii.gz, sub-ADNI011S1080_ses-M24_T1w_bia
s.nii.gz ]
Standard output:
Standard error:
 file ADNI_BIDS/sub-ADNI011S1080/ses-M24/anat/sub-ADNI011S1080_ses-M24_T1w.nii.gz does not exist . 
Segmentation fault (core dumped)
Return code: 139
```

**Comment by anbai106** [comment]
@Overnickel 
Thanks for you interests.

Though I'm not sure, but maybe this is caused by:
1) make sure that you have write permission in the folder of 'ADNI_BIDS'. The error of Core dumped sometimes is caused by this.
2) please check if it's correct that the --input-image for N4BiasFieldCorrection is correct. From the msg, it's not an absolute path. Per nipype rule, I think those image are simultaneously copied into the corresponding working directory. 

Hope this helps,

**Comment by chongming-ni** [comment]
> @Overnickel
> Thanks for you interests.
> 
> Though I'm not sure, but maybe this is caused by:
> 
> 1. make sure that you have write permission in the folder of 'ADNI_BIDS'. The error of Core dumped sometimes is caused by this.
> 2. please check if it's correct that the --input-image for N4BiasFieldCorrection is correct. From the msg, it's not an absolute path. Per nipype rule, I think those image are simultaneously copied into the corresponding working directory.
> 
> Hope this helps,

Thank! This problem is caused by the relative path. After I changed it to the absolute path, it was okay.
