### ISSUE TITLE
Issue with labels

### ISSUE THREAD

**Issue by sophieloiz** [aramis-lab/clinicadl#253]
When labels are different from the default one : AD/CN, TSV files can't be found.

**Comment by 14thibea** [comment]
Hello!
Just to be a bit more specific, does this problem arises when using `tsvtools` or `train` commands?
Do you have the error log?
Do you have the same error if you specify manually the names of the TSV files that must be loaded with the option `--diagnoses`?

**Comment by 14thibea** [comment]
I think the main problem is that currently the default option for TSV files detection is hard-coded to `["AD", "CN"]` in `resources/config/train_config.toml`.
Then if you don't precise anything it looks for TSV files named `AD.tsv` and `CN.tsv`...
This should actually be changed by refactoring the behaviour of `tsvtools` to be more general.

**Comment by sophieloiz** [comment]
This problem arises using the train command when manually specifying labels name with --diagnoses option. 

The error log is : 

Traceback (most recent call last):
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/bin/clinicadl", line 33, in <module>
    sys.exit(load_entry_point('clinicadl', 'console_scripts', 'clinicadl')())
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/click/core.py", line 1053, in main    rv = self.invoke(ctx)
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/click/core.py", line 1659, in invoke    return _process_result(sub_ctx.command.invoke(sub_ctx))  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/click/core.py", line 754, in invoke    return __callback(*args, **kwargs)
  File "/export/home/cse180022/gitlab_sophie/clinicadl/clinicadl/train/train_cli.py", line 373, in cli    train(output_maps_directory, train_dict, train_dict.pop("folds"))  File "/export/home/cse180022/gitlab_sophie/clinicadl/clinicadl/train/launch.py", line 7, in train
    maps_manager = MapsManager(maps_dir, train_dict, verbose="info")  File "/export/home/cse180022/gitlab_sophie/clinicadl/clinicadl/utils/maps_manager/maps_manager.py", line 75, in __init__    self._check_args(parameters)
  File "/export/home/cse180022/gitlab_sophie/clinicadl/clinicadl/utils/maps_manager/maps_manager.py", line 1111, in _check_args    train_df = split_manager[0]["train"]  File "/export/home/cse180022/gitlab_sophie/clinicadl/clinicadl/utils/split_manager/split_manager.py", line 92, in __getitem__
    train_df, valid_df = self.concatenate_diagnoses(item)  File "/export/home/cse180022/gitlab_sophie/clinicadl/clinicadl/utils/split_manager/split_manager.py", line 127, in concatenate_diagnoses    train_diagnosis_df = pd.read_csv(train_diagnosis_path, sep="\t")
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper    return func(*args, **kwargs)  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read    parser = TextFileReader(filepath_or_buffer, **kwds)  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__    self._engine = self._make_engine(self.engine)
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__    self._open_handles(src, kwds)
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles    errors=kwds.get("encoding_errors", "strict"),
  File "/export/home/cse180022/.user_conda/miniconda/envs/clinicadlDev_sophie/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/export/home/cse180022/apprimage_sophie/image_preprocessing_data/tier_2_vs_1/tsv_files/train_splits-5/split-0/[tier_1,tier_2].tsv'

**Comment by 14thibea** [comment]
Ok!
Can you write the command you launched also?
I think you have to put one flag per TSV file you want to load: `-d tier_1 -d tier_2` and not `-d tier_1 tier_2`.

**Comment by sophieloiz** [comment]
The command launched : 

clinicadl train classification /export/home/cse180022/apprimage_sophie/image_preprocessing_data/caps/  /export/home/cse180022/apprimage_sophie/image_preprocessing_data/caps/tensor_extraction/extract_1637332230.json /export/home/cse180022/apprimage_sophie/image_preprocessing_data/tier_2_vs_1/tsv_files/ /export/home/cse180022/apprimage_sophie/image_preprocessing_data/tier_2_vs_1/output_results_new_ --architecture Conv5_FC3 --n_splits 5 --diagnoses ["tier_1","tier_2"] --epochs 50

**Comment by 14thibea** [comment]
ok!
The problem comes from the way the `--diagnoses` flag is used.
Actually to give several arguments you have to put `--diagnoses tsv1 --diagnoses tsv2 ... --diagnoses tsvX`
Instead of writing `--diagnoses` you can also use the abbreviation `-d`.
Another to ensure that several arguments are correctly used is to write them in a TOML file.

**Comment by ravih18** [comment]
Seems to be solved and the general discussion is addressed in #311 .
