### ISSUE TITLE
clinicadl tsvtools get-labels not forming the merged.tsv file automatically

### ISSUE THREAD

**Issue by mselimata** [aramis-lab/clinicadl#435]
Hi, 
my clinicadl version is 1.3.1, in miniconda python3.8 environment, which is a separate environment and installed with default requirements.

As described in here https://clinicadl.readthedocs.io/en/latest/TSVTools I followed the tutorial, the script I used is 
```
clinicadl tsvtools get-labels /truba/home/meatay/ADNIT1w_BIDS/ /truba/home/meatay/labeldir/ --keep_smc

```
this code successfully creates the missing_mods folder but not creating merged.tsv (probably due to some bug clinica io-tools, I guess)
in the earlier version (specifically 1.2.0) I was able to form both missing_mods and merged.tsv also corresponding labels.tsv files without separately running the clinica io-tools merge-tsv command. 

23:15:22 - output of clinica iotools check-missing-modalities: /truba/home/meatay/labeldir/missing_mods
INFO:clinicadl.tsvtools.get_labels:output of clinica iotools check-missing-modalities: /truba/home/meatay/labeldir/missing_mods
23:15:22 - output of clinica iotools merge-tsv: /truba/home/meatay/labeldir/merged.tsv
INFO:clinicadl.tsvtools.get_labels:output of clinica iotools merge-tsv: /truba/home/meatay/labeldir/merged.tsv
Traceback (most recent call last):
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/tsvtools/get_labels/get_labels_cli.py", line 78, in cli
    get_labels(
  File "/truba/home/meatay/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/tsvtools/get_labels/get_labels.py", line 346, in get_labels
    raise ClinicaDLTSVError(f"{merged_tsv} file was not found. ")
clinicadl.utils.exceptions.ClinicaDLTSVError: /truba/home/meatay/labeldir/merged.tsv file was not found.

**Comment by mselimata** [comment]
This is not a major bug since it is possible to get the labels.tsv after subsequently running the necessary clinica iotools.
