### ISSUE TITLE
KeyError: 'CN'

### ISSUE THREAD

**Issue by mselimata** [aramis-lab/clinicadl#440]
Hi,
I am testing the pipeline with a small dataset, managed to train the default CNN model with default settings on AD & CN. Now I have a MAPS directory with the best model. 
I am currently able to use clinicadl version 1.2.0, pytorch 1.13.1
 the command I used is 
```clinicadl predict /home/msa/ADCNDL_image/ predict --caps_directory /home/msa/ADNI_CAPS/  --participants_tsv /home/msa/labels_baseline.tsv --overwrite```

When I run the prediction task I got the error below:
./predict.sh
14:02:10 - Path of json file: /home/msa/ADCNDL_image/groups/predict/maps.json
14:02:10 - Path of json file: /home/msa/ADCNDL_image/groups/predict/maps.json
14:02:10 - Prediction of split 0
14:02:10 - Prediction of split 0
Traceback (most recent call last):
  File "/home/msa/miniconda3/envs/clinicadl/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/predict/predict_cli.py", line 106, in cli
    predict(
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/predict/predict.py", line 59, in predict
    maps_manager.predict(
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/maps_manager/maps_manager.py", line 322, in predict
    data_test = return_dataset(
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/caps_dataset/data.py", line 762, in return_dataset
    return CapsDatasetImage(
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/caps_dataset/data.py", line 309, in __init__
    super().__init__(
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/caps_dataset/data.py", line 86, in __init__
    self.size = self[0]["image"].size()
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/caps_dataset/data.py", line 326, in __getitem__
    participant, session, cohort, _, label = self._get_meta_data(idx)
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/caps_dataset/data.py", line 209, in _get_meta_data
    label = self.label_fn(target)
  File "/home/msa/miniconda3/envs/clinicadl/lib/python3.8/site-packages/clinicadl/utils/caps_dataset/data.py", line 110, in label_fn
    return self.label_code[str(target)]
KeyError: 'CN'

**Comment by mselimata** [comment]
Additional info, model was trained using clinicadl version 1.2.0, python 3.8 environment.
With the recent clinicadl 1.3.1 I am getting the error below with the prediction command, I'll also try to train with the same version and test the prediction.
Traceback (most recent call last):
  File "/home/msa/miniconda3/envs/ClinicaDL-Dev/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/home/msa/miniconda3/envs/ClinicaDL-Dev/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/msa/miniconda3/envs/ClinicaDL-Dev/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/msa/miniconda3/envs/ClinicaDL-Dev/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/msa/miniconda3/envs/ClinicaDL-Dev/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/msa/miniconda3/envs/ClinicaDL-Dev/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/msa/clinicadl-dev/clinicadl/predict/predict_cli.py", line 113, in cli
    predict(
  File "/home/msa/clinicadl-dev/clinicadl/predict/predict.py", line 62, in predict
    maps_manager.predict(
  File "/home/msa/clinicadl-dev/clinicadl/utils/maps_manager/maps_manager.py", line 231, in predict
    size_reduction=self.size_reduction,
  File "/home/msa/clinicadl-dev/clinicadl/utils/maps_manager/maps_manager.py", line 114, in __getattr__
    raise AttributeError(f"'MapsManager' object has no attribute '{name}'")
AttributeError: 'MapsManager' object has no attribute 'size_reduction'
