### ISSUE TITLE
clinicadl tsvtools analysis error

### ISSUE THREAD

**Issue by mselimata** [aramis-lab/clinicadl#454]
Hi,
I tried to run the analysis command for the processed ADNI to make a table of the population info.
I ran the command below, I already rand the get-labels and have all the relevant tsv files ready.
clinicadl version is 1.4.0

`clinicadl tsvtools analysis /truba/home/meatay/CNN_training/labels/merged.tsv /truba/home/meatay/CNN_training/labels/labels.tsv /truba/home/meatay/CNN_training/labels/analysis.tsv --diagnoses AD --diagnoses CN `
Error message
```
/truba/home/meatay/clinicadl_test/clinicadl/tsvtools/analysis/analysis.py:50: DtypeWarning: Columns (24,448,755,756,758,761,762,763) have mixed types. Specify dt$
  merged_df = pd.read_csv(merged_tsv, sep="\t")
18:45:20 - Missing diagnoses: 5118
18:45:20 - Missing diagnoses not found: 5118
Traceback (most recent call last):
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/truba/home/meatay/miniconda3/envs/clinicadl_test/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/truba/home/meatay/clinicadl_test/clinicadl/tsvtools/analysis/analysis_cli.py", line 22, in cli
    demographics_analysis(merged_tsv, data_tsv, results_tsv, diagnoses)
  File "/truba/home/meatay/clinicadl_test/clinicadl/tsvtools/analysis/analysis.py", line 114, in demographics_analysis
    first_session_id = next_session(subject_df, first_session_id)
  File "/truba/home/meatay/clinicadl_test/clinicadl/utils/tsvtools_utils.py", line 81, in next_session
    raise IndexError("The argument session is the last session")
IndexError: The argument session is the last session


```

**Comment by camillebrianceau** [comment]
Hi @mselimata, 

Thank you for your interest in ClinicaDL!

Could you please provide the merged.tsv file? It seems that the error is occurring because the diagnoses are in float format, and it continues searching for a string diagnosis until the last session. Is it possible that this is the cause of the issue?

Best regards, 
Camille

**Comment by mselimata** [comment]
Thank you Camille,
Here is the merged.tsv file, it is produced by the `clinicadl tsvtools get-labels` command only, I did not use clinica io tools separately.
[merged_final.zip](https://github.com/aramis-lab/clinicadl/files/11903556/merged_final.zip)
Kind regards,
Melvin

**Comment by camillebrianceau** [comment]
Sorry I forgot to ask, but can I have the labels.tsv also please ?

**Comment by mselimata** [comment]
here you can get them, thank you for looking on this problem.
[labelsADCN.zip](https://github.com/aramis-lab/clinicadl/files/11905590/labelsADCN.zip)

**Comment by camillebrianceau** [comment]
Thanks ! 

It seems that the participant with the ID `sub-ADNI037S5162` only has one session, and their Clinical Dementia Rating (CDR) value is missing (NaN).

As a temporary resolution, I suggest removing the participant from the labelsADCN.tsv file. This should allow the pipeline to continue functioning properly. In the meantime, I will be working on a more permanent solution to address such cases

Thanks for your contribution in clinicaDL, 

Best regards, 
Camille

**Comment by mselimata** [comment]
Thanks, I'll let you know if I get any error after removing the subject.
