### ISSUE TITLE
unsupported operand type(s) for +=: 'PosixPath' and 'str'

### ISSUE THREAD

**Issue by mtmmu88** [aramis-lab/clinicadl#469]

**Comment by mtmmu88** [comment]
I'm running! Clinicadl train classification data/synthetic extract_ T1linear_ Image data/split/3_ Fold data/syntax_ Maps - Architecture Conv4_ FC3-- n_ When the split 3-- split 0 command is used, the prompt TypeError: unsupported operator type (s) for+=: 'PosixPath' and 'str' is displayed

**Comment by camillebrianceau** [comment]
Hi @mtmmu88 ! 

Thank you for your interest in ClinicaDL, 

Could you please provide the full error message ? 

Best regards,
Camille

**Comment by mtmmu88** [comment]
Thank you very much. I have been learning to use ClinicaDL software recently and was attracted by it. Yesterday, I ran the Clinicadl train classification data/synthetic extract from the tutorial_ T1linear_ Image data/split/3_ Fold data/syntax_ Maps - Architecture Conv4_ FC3-- n_ When the split 3- split 0 code, prompt:Traceback (most recent call last):
  File "/home/zzc/miniconda3/envs/ClinicaDL/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/train/tasks/classification_cli.py", line 79, in cli
    task_launcher("classification", task_specific_options, **kwargs)
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/train/tasks/task_utils.py", line 99, in task_launcher
    preprocessing_dict = read_preprocessing(preprocessing_json)
  File "/home/zzc/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/utils/preprocessing.py", line 26, in read_preprocessing
    json_path += ".json"
TypeError: unsupported operand type(s) for +=: 'PosixPath' and 'str'
I hope to reply in my busy schedule

**Comment by mtmmu88** [comment]
I added JSON from the clinicadl/utils/reprocessing. py file in the source code_ Path+=". json" changed to JSON_ Path=Path (str (json_path)+". json"), successfully running. Is this method feasible?

**Comment by ghisvail** [comment]
You can simplify this using [with_suffix](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_suffix):

```python
if not json_path.name.endswith(".json"):
    json_path = json_path.with_suffix(".json")
```

Feel free to submit a PR for it, and thank you for triaging this bug 👍
