### ISSUE TITLE
categorical split variable flag

### ISSUE THREAD

**Issue by mselimata** [aramis-lab/clinicadl#471]
Hi,
When I tried to use `--categorical_split_variable` for splitting using `clinicadl tsvtools split ` it does not accept any input and gives error. 
From my understanding this flag would be allowing stratified split of data which would keep the same ratio of the selected variable, is it correct?
Here is the error log for the input of `clinicadl tsvtools split /home/msa/ADCNqc/labels.tsv --n_test 0.4 --subset_name validation --categorical_split_variable CN`
```Traceback (most recent call last):
  File "/home/msa/miniconda3/envs/ClinicaDL/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/tsvtools/split/split_cli.py", line 79, in cli
    split_diagnoses(
  File "/home/msa/miniconda3/envs/ClinicaDL/lib/python3.8/site-packages/clinicadl/tsvtools/split/split.py", line 285, in split_diagnoses
    categorical_split_variable.append("diagnosis")
AttributeError: 'str' object has no attribute 'append'

**Comment by camillebrianceau** [comment]
Hi @mselimata,

Your understanding is correct but the `categorical_split_variable` has to be a column's name in your `labels.tsv` file. Is CN the name of a column in your example? Anyway, there is an error in the code that PR #475 should resolve. 

Bests, 
Camille
