### ISSUE TITLE
Requirement for 'diagnosis' Column in Generalization Testing with ClinicaDL

### ISSUE THREAD

**Issue by mtmmu88** [aramis-lab/clinicadl#481]
Dear ClinicaDL Team,

I have encountered some issues while using ClinicaDL for neuroimaging analysis. Specifically, I am interested in using your tool to test the generalization capability of a pre-trained model. The issue arises when running the clinicadl predict command, which seems to require a TSV file containing a 'diagnosis' column.

In the context of generalization testing, diagnostic information is often either unavailable or irrelevant. Therefore, I am wondering if there is a way to perform generalization tests without providing a 'diagnosis' column.

If such a feature or option does not currently exist, I strongly suggest adding it as a new feature or option. This would greatly enhance the flexibility of ClinicaDL in practical applications.

Thank you very much for your time and consideration.

Best regards

**Comment by mtmmu88** [comment]
clinicadl predict /root/autodl-tmp/map  'test-Oasis3' --participants_tsv  /root/autodl-tmp/test/data.tsv --caps_directory /root/autodl-tmp/test/CAPS_example
Traceback (most recent call last):
  File "/root/miniconda3/envs/ClinicaDL/bin/clinicadl", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/clinicadl/predict/predict_cli.py", line 120, in cli
    predict(
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/clinicadl/predict/predict.py", line 64, in predict
    maps_manager.predict(
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/clinicadl/utils/maps_manager/maps_manager.py", line 240, in predict
    group_df = load_data_test(
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/clinicadl/utils/caps_dataset/data.py", line 1141, in load_data_test
    test_df = load_data_test_single(test_path, diagnoses_list, baseline=baseline)
  File "/root/miniconda3/envs/ClinicaDL/lib/python3.10/site-packages/clinicadl/utils/caps_dataset/data.py", line 1151, in load_data_test_single
    raise ClinicaDLTSVError(
clinicadl.utils.exceptions.ClinicaDLTSVError: 'diagnosis' column must be present in TSV file /root/autodl-tmp/test/data.tsv.  
this is my bug

**Comment by camillebrianceau** [comment]
No longer relevant with the v2.0.0.
