### ISSUE TITLE
Error when installing with pip

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinicadl#81]
I got an error while installing with pip the latest version of master:

```
Obtaining file:///Users/elina.thibeausutre/Documents/code/AD-DL_doc/clinicadl
    ERROR: Command errored out with exit status 1:
     command: /Users/elina.thibeausutre/miniconda2/envs/clinicadl_doc/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/elina.thibeausutre/Documents/code/AD-DL_doc/clinicadl/setup.py'"'"'; __file__='"'"'/Users/elina.thibeausutre/Documents/code/AD-DL_doc/clinicadl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/j4/pt6zgm1102913npryfnj439c000mkt/T/pip-pip-egg-info-ossi3_vv
         cwd: /Users/elina.thibeausutre/Documents/code/AD-DL_doc/clinicadl/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/elina.thibeausutre/Documents/code/AD-DL_doc/clinicadl/setup.py", line 16, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/Users/elina.thibeausutre/Documents/code/AD-DL_doc/clinicadl/setup.py", line 16, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I commented lines 17 and 46 and everything went well.
My version of pip is 20.1.1

**Comment by alexandreroutier** [comment]
This issue is also present in Clinica (https://github.com/aramis-lab/clinica/issues/102).

We have two ways to solve this issue. Let's wait @mdiazmel's opinion next week regarding the best solution to apply 🤔

**Comment by mdiazmel** [comment]
Hi guys,
It seem that there are changes in the function `pip._internal.req` in the recent versions of setuptools. In fact, this function don't be used to parse the requirements file (is an internal method from pip, it can change anytime). I'll try to see some alternatives.

**Comment by 14thibea** [comment]
This problem was solved.
